name: KUC test execution

on:
  workflow_call:

jobs:
  kuc-tests-execution:
    name: ${{ matrix.runner || 'SKIP' }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Create a File
        run: echo "hello from ${{ matrix.runner }}" >> $GITHUB_ENV
      - name: Upload allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure_results_${{ matrix.runs-on }}
          path: allure-results
          if-no-files-found: ignore
